model_path: models/yolov8n.pt
conf_threshold: 0.7
iou_threshold: 0.45
device: cpu
img_size: 640
class_names:
  0: CONFORME
  1: VEC
  2: SCRAP
  3: RETRABAJO
roi:
  enabled: true
  x1: 1200
  y1: 100
  x2: 1700
  y2: 900
